# Use official OpenJDK 17 image
FROM eclipse-temurin:17-jdk-alpine

# Set a working directory
WORKDIR /app

# Copy the built JAR into the container
COPY target/Expense-Tracker-0.0.1-SNAPSHOT.jar app.jar

# Expose the port your app runs on
EXPOSE 8080

# Run the JAR
ENTRYPOINT ["java", "-jar", "app.jar"]
